version: '3'

services:
  web:
    build:
      context: .
      target: web
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/localhost.pfx
    ports:
      - "443:5001"
    links:
      - dda-grpc
      - fdtd-grpc
  dda-grpc:
    build:
      context: .
      target: dda-grpc
    ports:
      - "3001:3001"
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:3001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/dda-grpc.pfx
  fdtd-grpc:
    build:
      context: .
      target: fdtd-grpc
    ports:
      - "3002:3002"
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:3002
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/fdtd-grpc.pfx
